### ISSUE TITLE
Flake Refactoring

### ISSUE THREAD

**Issue by Qeatrix** [Qeatrix/nixos-config#2]
# Refactor The Entire Flake
This flake needs code refactoring due to poor code structuring

# Todo
- [ ] System directory with main configuration file
- [ ] Services in system
- [ ] Programs whose options are available only in NixOS in system
- [ ] Hardware-specific options in system
- [x] Home directory with all my DEs and WMs environments
- [x] Overlays in home
- [x] Interface customization in home
- [ ] https://github.com/Qeatrix/nixos-config/issues/3
- [x] Packages directory with custom builds
- [x] OS and Home-Manager separation
